---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: telegram
type: Opaque
stringData:
  BOT_TOKEN: ENC[AES256_GCM,data:mn3WNGWJMtXshlcAl2I5k0Heu4OUg1a2sFX4Kbv+58MTSo2aLRCEgpGJzNvQbg==,iv:5EOSnez/3GciYwXceeotVEaQq2lxPstPu0ZQjik3PuY=,tag:Zox3Lw3dTL1/MS5O0TH41w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdGtOeVhuNFNxdFVmR1Uw
        VnlHNUJ5TEQ3SkZYMWhOc0VjOVVNOVhaNWdrClB0YlRMOWZWTnRyWjdQMUhJaUVs
        eFB3eENtUUJuRFpzZjYyNXNIaTJacHcKLS0tIGh1K1dMS0pZMHN5WUEwZkNvQkFp
        ZEpRODczdHNvZHdudVFYdzRpWTRrc2cKiNYVhWIDBeLeU5uTvlC7sX0cLqABFl1I
        rZe5Nrq9vtW5RXUMT0zLjSWzPkKeO1tSRGNuzbpgpSkaYiwkcKzZsw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-07T05:51:27Z"
  mac: ENC[AES256_GCM,data:NMnCR1x5XC/qQKOUAL9c2xchqrwq/GEdbuFz8o1U6a5DE3PfQuCHT2R97nJr4K/EyvjAcnikmQd0jiTdJJxsdGDE39CCJ8+bxl3RdhAyK1/fJUNxv5hDGj0QWatvNb+tH6GdHB0r2gaazn/FroXu9gcnBmWBIiXgfCbsb8+LAj4=,iv:5SPNipVwEVyLRKmSOjTwqC1ebP4PrgOdpXZ0k0ZdlLM=,tag:JVkBH4krVlW7CZThY5Bt/w==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
