---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: rook-ceph-cluster
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.19.6
  url: oci://ghcr.io/rook/rook-ceph-cluster
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  interval: 1h
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: rook-ceph-cluster
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: volsync
      namespace: storage
  values:
    monitoring:
      enabled: true
      createPrometheusRules: true
      prometheusRuleOverrides:
        CephNodeDiskspaceWarning: # So many false positives
          disabled: true
        CephPoolGrowthWarning: # Causing errors in VMAlert
          disabled: true
        CephNodeNetworkPacketDrops:
          disabled: true
    toolbox:
      enabled: true
    route:
      dashboard:
        host:
          name: "rook.${CLUSTER_DOMAIN}"
          path: /
          pathType: PathPrefix
        parentRefs:
          - name: envoy-internal
            namespace: network

    cephClusterSpec:
      dashboard:
        enabled: true
        urlPrefix: /
        ssl: false
        prometheusEndpoint: http://vmsingle-vmetrics.observability.svc.cluster.local:8428
      cephConfig:
        global:
          bdev_enable_discard: "true" # quote
          bdev_async_discard_threads: "1" # quote
          osd_class_update_on_start: "false" # quote
          # Cant enable due to `Module 'diskprediction_local' has failed: No module named 'sklearn.svm.classes'`
          # device_failure_prediction_mode: local # requires mgr module
      cleanupPolicy:
        wipeDevicesFromOtherClusters: true
        # confirmation: "yes-really-destroy-data"
      crashCollector:
        disable: false
      csi:
        readAffinity:
          enabled: true
      mgr:
        modules:
          # Cant enable due to `Module 'diskprediction_local' has failed: No module named 'sklearn.svm.classes'`
          - name: diskprediction_local
            enabled: false
          - name: insights
            enabled: true
          - name: pg_autoscaler
            enabled: true
          - name: rook
            enabled: true
          - name: prometheus
            enabled: true
          - name: stats
            enabled: true
      network:
        provider: host
        connections:
          requireMsgr2: true
      storage:
        useAllNodes: false
        useAllDevices: false
        # devicePathFilter: "/dev/disk/by-id/(ata-SAMSUNG_MZ7KM|ata-SSDSC2KG480G8R_PHY|ata-SAMSUNG_MZ7LH)*" # List these with: `talosctl get disks` then get name of disk and do `talosctl get disk diskname -o yaml` and check spec.symlinks
        nodes:
          - name: "kube-srv-01"
            devices:
              - name: "/dev/disk/by-partlabel/r-osd-01" # Samsung PM963 1.92TB SATA
          - name: "kube-srv-02"
            devices:
              - name: "/dev/disk/by-partlabel/r-osd-01" # Samsung PM983 1.92TB NVME
          - name: "kube-srv-03"
            devices:
              - name: "/dev/disk/by-partlabel/r-osd-01" # Samsung PM963 1.92TB SATA
        config:
          osdsPerDevice: "1"
      resources:
        mgr:
          limits:
            memory: 700Mi
          requests:
            memory: 700Mi
            cpu: 100m
        mon:
          limits:
            memory: 768Mi
          requests:
            cpu: 100m
            memory: 768Mi
        osd:
          limits:
            memory: 6Gi
          requests:
            cpu: 150m
            memory: 6Gi
        prepareosd:
          limits:
            memory: 3000Mi
          requests:
            cpu: 50m
            memory: 200Mi
        mgr-sidecar:
          limits:
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 40Mi
        crashcollector:
          limits:
            memory: 64M
          requests:
            cpu: 15m
            memory: 32M
        logcollector:
          limits:
            memory: 32Mi
          requests:
            cpu: 5m
            memory: 16Mi
        cleanup:
          limits:
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: host
          replicated:
            size: 3
        storageClass:
          enabled: true
          name: ceph-block
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          volumeBindingMode: Immediate
          mountOptions:
            - "discard"
          parameters:
            compression_mode: aggressive
            compression_algorithm: zstd
            imageFormat: "2"
            imageFeatures: layering,fast-diff,object-map,deep-flatten,exclusive-lock
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/fstype: ext4

    cephBlockPoolsVolumeSnapshotClass:
      enabled: true
      name: csi-ceph-blockpool
      isDefault: false
      deletionPolicy: Delete
      allowVolumeExpansion: true
      volumeBindingMode: Immediate
      mountOptions:
        - "discard"

    cephFileSystems: []
    cephObjectStores: []
