---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: vm-operator-chart
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.63.1
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-operator
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vm-operator
  namespace: vm-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: vm-operator-chart
  maxHistory: 2
  install:
    crds: CreateReplace
    remediation:
      retries: 3
    timeout: 15m
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      image:
        registry: mirror.gcr.io
    crds:
      enabled: true
      cleanup:
        enabled: true
    operator:
      # -- By default, operator converts prometheus-operator objects.
      disable_prometheus_converter: false
      # -- Compare-options and sync-options for prometheus objects converted by operator for properly use with ArgoCD
      prometheus_converter_add_argocd_ignore_annotations: false
      # -- Enables ownership reference for converted prometheus-operator objects,
      # it will remove corresponding victoria-metrics objects in case of deletion prometheus one.
      enable_converter_ownership: true

    serviceMonitor:
      enabled: true
      # -- Creates `VMServiceScrape` if `true` and `ServiceMonitor` otherwise. Make sure [Prometheus Operator CRDs](https://artifacthub.io/packages/helm/prometheus-community/prometheus-operator-crds) are installed if it's set to `false`
      vm: true
