---
# Losing SECRET_KEY makes every stored integration token and API key unreadable.
#
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: outline-secret
stringData:
  SECRET_KEY: ENC[AES256_GCM,data:JpO73n0WvKx4BQijFqEZoHq8zzbawSf91HYOPPkk5u4ZIMCmLXfv0MIZzEP6+/JIYZC8tByHp62YggBnXzUIPw==,iv:N1HmwkovdLaWx+rQG6tgD5al+vGeEJmQ5FQFRwHYnn4=,tag:a/rV2u79uOF3wvWybl/Fdw==,type:str]
  UTILS_SECRET: ENC[AES256_GCM,data:Y0xInIGV/1z9F9Bqrg2h/2NI45OztV5A1nT/dCFKa28BipH3XTLNRe9yORz4CJQ4iSGBjmuwk2u2l4tyRbG76Q==,iv:kydorXHTB24xVh9gqOE8WnWGYs7lnLN6GYRmVrDaY5I=,tag:EZ+n0ST5zyPIsIV/Ey44pQ==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:hrzQViCSwc0=,iv:e0EDt4tSQ516GlEfxEfvTfUJQQFzgVt5gd+Uq/dPqHk=,tag:PDBPPPDbOdH3YLOpWOsWwQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMFQ3ZXg3UzMyMWpUeFZw
        Rnk4bVdZcHlLQ2llaENiUjd1VnJvQWlYS0hjCnpyUmxkbjR0T2VrejZjaU1mMTFN
        K21IalpuVkdjbENhSGp5T0JHTzNZcWcKLS0tIEQ2M1o4b3hrUjBqcHQwdTlJK3Nq
        VjFwamRUZlUweHpKOXRwTDVFK0dEVEkK4b59w+UxwYdoNtTafzVt69jmCPv6IZbr
        4htBuxHp9/09teaJIgvs2DZgK197tRS0Jz+uGDF9PrFRsi0qa2GWiQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-07T14:37:34Z"
  mac: ENC[AES256_GCM,data:fzxmEzYT3vai/MXY6CqstUmYctgiGO262UYde2tSn4YxsGC/far5FUJzv6QDVslD6e/+4UELXw5aYyd021xqXZq6ZS0ii6Xi5OvhD1RMSMo6OmmPFFecHTLBynSZsjmuA1y7HE8S7bAKIi+EG+LYyLfmDsQv3YekNxWSgNssRyk=,iv:hhcGc2uYWi8qLf+RzzZo+ip02SO9pQd1ZkYNpxHHNDs=,tag:Zn5xT35ivX1YbaD2rEDgVQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
