---
# Losing SECRET_KEY makes every stored integration token and API key unreadable.
#
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: outline-secret
stringData:
  SECRET_KEY: ENC[AES256_GCM,data:JpO73n0WvKx4BQijFqEZoHq8zzbawSf91HYOPPkk5u4ZIMCmLXfv0MIZzEP6+/JIYZC8tByHp62YggBnXzUIPw==,iv:N1HmwkovdLaWx+rQG6tgD5al+vGeEJmQ5FQFRwHYnn4=,tag:a/rV2u79uOF3wvWybl/Fdw==,type:str]
  UTILS_SECRET: ENC[AES256_GCM,data:Y0xInIGV/1z9F9Bqrg2h/2NI45OztV5A1nT/dCFKa28BipH3XTLNRe9yORz4CJQ4iSGBjmuwk2u2l4tyRbG76Q==,iv:kydorXHTB24xVh9gqOE8WnWGYs7lnLN6GYRmVrDaY5I=,tag:EZ+n0ST5zyPIsIV/Ey44pQ==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:buwuekBHrFAEgCmN6tUY9Y0bVSSI2+IDJLHcgyqgK2fVA+XB7eUtzA==,iv:CmRZPHyvQWxol5vr5c3+VjUAdroP3FEUNq+6w4zsMos=,tag:QoouiDszdeKijKOY/b0wIA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMFQ3ZXg3UzMyMWpUeFZw
        Rnk4bVdZcHlLQ2llaENiUjd1VnJvQWlYS0hjCnpyUmxkbjR0T2VrejZjaU1mMTFN
        K21IalpuVkdjbENhSGp5T0JHTzNZcWcKLS0tIEQ2M1o4b3hrUjBqcHQwdTlJK3Nq
        VjFwamRUZlUweHpKOXRwTDVFK0dEVEkK4b59w+UxwYdoNtTafzVt69jmCPv6IZbr
        4htBuxHp9/09teaJIgvs2DZgK197tRS0Jz+uGDF9PrFRsi0qa2GWiQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-07T15:11:35Z"
  mac: ENC[AES256_GCM,data:Xfeg2WkazYmSZmq56QvKhodt0dZgL1mMVG6XKXEkMwy+kYWkv7/s5tkAnAzEOdD/00ws//U5nWVCY0GbKOehMl96BozrPXdDLwNI+w7a4p/pyVJqAN103DeQ9mEYFbC6DbAtcbnCPNM7Zs/7pRyF6y0PaZ/szXFdSprW8WCfshE=,iv:ZQ0BQXktwio44fjJO2EkpRB9UZ7UAQgsI/16HFuW31s=,tag:jLpta5+TQRnQyu4cCDUFWw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
