---
apiVersion: v1
kind: Secret
metadata:
  name: kguardian-mcp-token
stringData:
  #ENC[AES256_GCM,data:mQudyUsC+BspSgS09G5nSOwmlmHpYI16lMMT3rIA9u8EXNY3zH+ulzcNxt1dew0KPFKa5GppbDAgVdRgdFtgFwifb/pmYuOp8Zo=,iv:Zobo8kwy2OQvwMi2D1T6LMcZoi5z2tSViotTSNAcxVk=,tag:5ugDYhP/yyxfM5gu3kNwKQ==,type:comment]
  token: ENC[AES256_GCM,data:W5jy8sUHk1v6AwVwJunmlWcIJz1nQdHNUWJ1i1O3TSjrT2wTS+21m/RQuFqvCXidWndCTjL9M+PhOQgyWicqiQ==,iv:mmKvLE2aaIQdcAe7oY3jA2LJk633uN9ZOhKXAGsA8qw=,tag:9Ofripm38XvhN8Hk8pt3xg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWc2xrNzlVeEpxUk0wTG5x
        cGYrS0orRWszT2Y5dDI4cElmMER1ODc4T0VNCmgxMzhMbnNEczBuZVg0WGdhMDNl
        dDM1dTdzc25rbWdmazNZVXJ3b0dHRXMKLS0tIFI2N2pFbWpucEJrY29sWVFSMS96
        SHFFbUNYQm9JV0RLVS9hb0NFaWhTWFEKwlZQFBcPhFu0YY/LstioUysZkByu4S60
        YSER3eb+y7BhYnoJUzu2PuKxuBS5Ajltgrk9FztyEwBOXHzWpynfNw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-15T10:51:38Z"
  mac: ENC[AES256_GCM,data:GwA4DdBfOvCsEVyTwp2nF3l/gO+/3dQ5nK9ZKfjUmC6SBeJWUdB2ZTWGoaFX50QL2MJDPazUu/07JvTLdtrlpchwuHklWXNnx4vFb/TIh29N+YnxsnzDq3LeMDVbeVfiyqe6Zfj3Ot0UtR06/mJCs4K+pN/Vun41Y99NBD7EtX4=,iv:X5bk/XF1efx27hh1nd8oy5sNgGAf5qIqLG3fdAtGd/0=,tag:qgb6gkOwFgp+lnQScx5MGQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
