---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: dvinyl-discogs
stringData:
  DISCOGS_TOKEN: ENC[AES256_GCM,data:Jesfg1+GDmtGIC/yLfCPWuKGkwmTrfcRfAHWRAReEUhUKfHWkX/9rQ==,iv:e6SKcrNA4cFKqWfnoi3u47UnCpIbm3+yrCzHuazvamk=,tag:WHA8LbJl5CL0pXZdX9NkHg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVjhmMlFLTXFwRGpNVXgx
        cWRUTDFsdG82MnZrR2pWR1UvVlNSajB3NnhJClBGc2tNMHdtamdIRC80TEJiK3ha
        cEx6QW50TDN2NlVSaUh1YnMwTDhIU0EKLS0tIEd0RkhMNDlITms5OUpodWhjNElG
        UWROYkk4V0d4YmdFTUFINVdwQVUyeFkKninmCUjgX4KiWfD/RQjUTVPKsYsQQpG+
        rElN7+SeBsQ7a+H6zxZMPD8kQoOr03Zydm2hJkTe1TTV4fj5iNxrOg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-02T14:10:06Z"
  mac: ENC[AES256_GCM,data:5l6N9HgTf5ANpTwMYZlFm6R+KBYBMKAtLpKUs3EwkTsasAyyXK5Glika3oED4XsBmq+BqEQWdninjkHae7Cqd4IkhI4e6sxTwMRJhcunzOHxYI6Ut/Kf//vxH0zTyH8MNNb6kDvDZEPsGAveygtllGJkxQ9I8VTI+fc1UriLiDg=,iv:JHQyWeVkdbhxemEeI9BxFMqUn79nYwDdvo9oNpwlDf0=,tag:WyVjSdcEHvN2PNBOn5S3Vw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
