---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:jNO9cjiIWTQnuqF0wMLcesUdp9LXy6mhlFL6ipdGqKfOe8XgqPFsVA==,iv:GGFjw8uC2aDEhGvPlSyq8G8HqMBfR1ebGID//8ANvcI=,tag:fedTQMmnPu3G4qCBU211gQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUWt0TzFUQU5obks1TWN0
        VEJhV2xnTk5EMzhGTXRyeXFQc2p6OHNmTUQ4CnZoN1UzUFJVV09IVzgvaTgwVTRC
        bGdtazhuK002eTE0bm5ZdDlVWUxrcEUKLS0tIHpEZVpNeWpYR1laZ0t3ckdKOFda
        ak10dEJiNjZpVG9sSTFFN2JFazVTWkUKmDDklXj18ASelraBLrxGb8SqFSlcNJ5n
        SXQQ4Eki0YNsL+6tSbe0Hb00u+mRPaAaQBtaCj9D+Wy+qhq9UZmS4A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T19:50:04Z"
  mac: ENC[AES256_GCM,data:MLSpO6VsFiCA/gaQY0wddSNsEPNdD3Wdegd4QoTme3jtl1sFR+b6rLqiWG7ahLlKIvc/gw/xPJM2DVIrdIU7c7lQzDE6BqYnxnb2mhuWRMIeongGLJIP79jJ8kyPubD4SSqLwagf8I5dlyVfOg1skXyR46a6k9RZPKK52cdwi8w=,iv:7m5lPUJO9XQgV14U16w7cskcVQQPB4q1FStZC65ojk0=,tag:r6JeLuKZWNUABgjRM7g5XA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
