---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Cj601xpiVs4KpFimjWPvAbQAR8xyfyaavaEwJX9sTZj6L2i9KaxzFA==,iv:JIxNAsL5Wm9k8F9umK0b0BzPu9ezDqstGKbX/UWzay4=,tag:UcTj/Muhgwc8sbiGH1jfAA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwa2MrQnBneXBDMWg2THkz
        bk51NHY0cTZLY1RvUnJselFDZjlFQUl2RFN3ClFubGZmOEl4VlNBTlVrMjVCb0hW
        R3k1eXNGSm9Jd1g5WmlsMlcxOHFxZDQKLS0tIHNqdDZBVGNmSGtpQ2dsWi84Vlk4
        a3ljVFB4TWFCQllIRjBoT2c1SUlBMncKBBAHxJdVkb6or2/uTqG2gQC8+Djb/rjC
        Lkt+DDfuUiX2GHgLqfzBlkuXbOdb6YtPT6rVgtrkhS4GNQSP6KOSAg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-05T13:56:31Z"
  mac: ENC[AES256_GCM,data:DIONIaFRCJnLWhPjPgr9c72pBNxncAJiccVXvfJC12ZQFR8KheajLWR4O/n3o1IwA9+UghBR4qrPPjFlRtXPAlXv+AzYqQonP9ZRrxvap3r3gH3Uv1Cbp0qDMsuT78WghvQ4K4QHUg7gBFQz604AXPRGV6HQ6lT9opHfEJaMFxw=,iv:I4ucWDH288Dc/6tba2RP4TUKmfQLS4bn2YwMtuBpP1o=,tag:pFri+n0fo4AYDimZm1hTSA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
