---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:KCx3VEczDxxyUOZvrRdkzSeQjukaeC1tiHmVR7UPNA+J0A5kmMY1/A==,iv:VnbMXSZ2tW+S1ShZO/aAVJm+eCTikqf3mn8/Ee3Wh4A=,tag:s/aztn3ncthss1HNXCWZ7w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NC9JM3NwOXFKQU4wYlB1
        M2JHMzJsOFAwZjFmK0ZwcWRnWlpSNmJ1WWgwClRDMFJydkU0bEoxdzFaUEllNTZT
        MVYvZDFQK2JGSmZJRy8vSTRPeHFxSkkKLS0tIHhaSGZ0cTBob0l2WlZJZXZabWNo
        ZTF4RnN4bUhVVDdsWXArRHV6a1FFTFkKHIA5J/AiUrnPL/fgDipiv4Ynf/T1YoQV
        wjQHKC9npr74FJJn9FEHTlRDPu1AXVOxy2FaXZGR1aabp1Bnf9SKsw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-06T18:20:50Z"
  mac: ENC[AES256_GCM,data:6osjcAgaArTQLgWUnpFa1g+d+N4FYdRg9HUYxE8qhSQcaykyEInMDGpUNJipprHbUb1AxjxQoQ0TpEkpNVv78GRrPCUwC79UZlK7Uwyzxtrt8J4JRnQDeOcvdBg2D+MKoh/18fuXPY8Ko3KpXzEZatZL2buk5dNxU/LMBJWUJUI=,iv:YDQirveZ8iKyvaLXSWC9B4jBLg71Rf9NOcGKKpdikNs=,tag:V3vz9En1jpalV/Txs+IAKg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
