---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:08fw1D+bHLua,iv:ZibeltTS9Q3uTwbEiVQzmoRGLKwBFFjnX9QCIGZeOrg=,tag:o1IB6IQlYQOdwMJDZTDydw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RklrU2ZXYnJiMjBoLzFC
        dTNNMTRjeHJmY2JnQUxsekszMGg3N1RRRVhJCjBtdWJmUHRTdldmWHVRTmZ2dGNY
        WmU5anloWVVFQ1FjOGlrSUhNM0FSV0UKLS0tIGRhMkx1ZFFOYXFuNUFTNk1Sb1hH
        YWRCVXJ6V1A1emRqc2JxTU5kYmhTcTQK+SqMa4u0RQV5Q4zPlhbIt90/FCysM2fH
        ilLDEsdCFPHEurUI3vTRWNrFO2o4LWYvTF2mZ1VQYBjVaKrDTSmE5g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T19:45:58Z"
  mac: ENC[AES256_GCM,data:2YEppm84tka/THCkLpRlsmJyGhXLV8q5/UImZie8Zo//zhgK2O0Uk/gkDRSUCVyU2h2muvl2X15JcqrMZ/2SXNOaxJmgiO+EJiAGqSvFhQAFCsKPoCfOTGtqdvNYSe26EjmpShuaYS8/hjRE90KfiiZeAC22X9a/zaLk2hj9JSo=,iv:6rg9Z0lyL5ZVS1wQrZS7UdASN0qidvXmmJx5DsAI5/U=,tag:25xXnAfhS6P8Dme9+X+3gQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
