---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:6zxyjjcc5wf8,iv:uY7i4J20FoaH/or86K18IL9CUSyMU0aDRKzlpw+kr5A=,tag:Ee5nY2mH8btabA7BdjXi+w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUlFvcFpoajI5cVk0VkZE
        YnhoLzFKeEx4UHE1eG82dVAvcmFpWnV1c0FJClBYQU8wd0Jhd0NxdkR3THJXODcx
        RzFZLzd1OThRMkphRzYyZFBIVGp3MDAKLS0tIFdiVDNodDEvMG50SEZNcGpuaCtB
        WmJNOTN5ZWQveDRaNlhUV3A0VnBkM00K/k7x4JfCezeXpQU2BO+zZ4xQA14Q7taB
        p1vtGpzv7NRNsAq/33TvquccRPK1LPQJX5QmRdTlwTBLDWUM+rBeFA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T20:19:44Z"
  mac: ENC[AES256_GCM,data:Uzj/YjwOmIEM/W9pjQFao7F63we6BOAOggUm6BvXpdmY6ZQwhB9ilkx4PpbiWzH/zv9WlA5AkXdAtTsZyXjF/3uPOv2jjl9ry1AkzZTNEIsMcNmjtY6MEFtmbd2+Vw6M+L183ZuWL+XQkMpaMhn+U+MK/NdA6VXa18BhZbr25Wc=,iv:JX+3ZR+jfd2G06uHnwi9XqRqSI3itvtLOhp7dnJebQY=,tag:kCjLjCMCAgFkwYuM7vlvHA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
