---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Irfy8cIfnDUu,iv:mLn3ghfjR5nCzG8BxWFi7W/iqps+QucrBZ6eePKSwac=,tag:LPqL8/CsrMNQY4mQ4Kozrg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5d1dHOUNLcVJRak9XZ3dT
        RjI4Yy9pbmx5VTd2YzBSR2tsQnpGUWFQSmdZCnF3ckI0UlhNL2sxQ1h3QVI1RG5M
        ZmZaMFVSdkMyeDVJeDVlWStLclIzZncKLS0tIDhWVmpuK1BuRUVxREx0NlZUVDI2
        WEtZd2lweEZXWWlaWThzczA4bitFdmMKRn20MzMZe4HW9ZtT5NsCDyUC/PSYy3uT
        VAznCKhEiaChMhA9yKOMfzJUgl8cCLOC1oQAx7kE6TAjZqpPdTu0sw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T19:50:04Z"
  mac: ENC[AES256_GCM,data:kGTpGWXzfQYnfgwdenobj0+oVWbtfFqu6te4f1ufI/Qln1f7T9BF+NVVlkmEuevfRp/qtDeFm79LL7oDKElrbCCWryEulYF2pWfg9WpRqGBxOuk9dyvcAHwwlSvrtpbZ9VJR67t99HTjVN3fJhi12FabfJl67ZlkieB6Iz+mu2Q=,iv:61HQrfjepHzalkKUk+hinR3ppuTbXK9+2prvLlEZRy0=,tag:BKD5gC2NPXXVu3f7qwcCeQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
