---
apiVersion: v1
kind: Secret
metadata:
  name: konflate-secret
stringData:
  #ENC[AES256_GCM,data:iKgcBORiI6DvIH1R8Z0f1WJmNSuDtxPTlHSMOYnymVqP4rwleijoi2XbBcvDsWilLPRQRY3v6itoMDYNuM09,iv:G3vhKu3BM4shyyuCark589Lk2nUT8k9odEw7zoxBtl4=,tag:gSGaHcoQq3SRqJ3u+P8BOg==,type:comment]
  KONFLATE_TOKEN: ENC[AES256_GCM,data:O/oVE4hBLTSJ7j/YyT7ZPu5TPWMQdFSLi4h2r3FT1KWjQFm2G9QAiXsLXig5KpPNeMJuDpsEg1yhvnjeenPlGsgWaLfNuxq9+gyxO4pgPZFFgdXC2VnNfxLOvRWm,iv:ZM9ZoxP6RkrJ+/Zps6QZ/YNJNDNNemN0kxV69xIXMI4=,tag:ev3v0KNSTJZ/H/d9+2mtTQ==,type:str]
  #ENC[AES256_GCM,data:/tfaVyXvonlfsDeSmoVYtjAdoC842mgS7w89dN+bS5cdsVoM921h0eeKeLwgZeVn/K2S+vy1vtevI6hkDdI=,iv:ylObuQLKvBU80teRBuVA7UukFeFHAzFYq8xLNZVpGnQ=,tag:17PZ7E2OCYWEGl7ms9m61g==,type:comment]
  KONFLATE_WRITE_TOKEN: ENC[AES256_GCM,data:DG7i3WfoPvI96YRsq1lo6miYHXobxOIJkgjAHY04p2SnlOY08TFnoQhSvRQAgZ6hs5NvWoAnyVsJ2yyTOxiQng7jpsMAq7X5SnHYRsc9KIynoH/oUk/qpO8dKedz,iv:yQ8mylL5xGv7fp5eXrbWYrc3d1wpNkDK7l78HHk8NNo=,tag:S+DZxHJs7HHvA7bdLTAUhA==,type:str]
  KONFLATE_WEBHOOK_SECRET: ENC[AES256_GCM,data:GRJfgpwisq08xCpzmSgZa+GHbz80UvKUutAZYFoXf8Epn3sOWT7MNQYzamBcl+AaHKwRvKskD/wYBs+en5o9og==,iv:hc9Mf2KL3aiwpE87cR6MtzcXwc5YTniRm2J7rVgCBbU=,tag:xqdIOtZBbMti3PQL8api2Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWGZiZVdnZFFMQytBZkJt
        TnVUZkZjM3B1eVhmV1FWTWNkOGxZa0c5dkc4Ck9QRHk1QXc3TEJTUWJoVWhCdFdy
        MlN1VDlkalF4VGZxMG9UdFBYMkh6NHcKLS0tIFVtTW15UHBjKy93eVRjME13L2xu
        dEJWOFFjZS9sNUtyS2VQK24vWlQ4cU0KKFrce12PR0StbO1jqILPqPprn93ZqJnH
        tHbk2OWPYppFOHyC2UWO7HQ42Vr34kdIUF3VfdvwQhWLlXqbH+L4UA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-27T09:25:51Z"
  mac: ENC[AES256_GCM,data:IzhA+hT9xZccIpPnSIPNkdNQQFtv1yeY3fEdyblUkDmGe7s6UEVZA9+Fj6WhVlBpWqkMvjJIS69mf80YrvBBCq5r+6i5idXSOSmIentqahSDf61C/Bq/B+c7Wg5bf/s15TGeM75TUmd1ea0pAa1aoARowM0veaoXzUpghRiirHA=,iv:NIKYV4N2WQ6yPgoRn4kWIgptW+PXypRJQKbNPVpnEG8=,tag:St/s9/kt413ekdLDmY8gGg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
