---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: authentik-tofu
type: Opaque
stringData:
  #ENC[AES256_GCM,data:6WqimlWYkXIobtFKiOs//slXH2S8RX/uK56E3jwA+xuHmhc1/2PDYeUfhkdaNd5Jt3A1kxlbOkyrRZ5wCeNsjcAzyjZBcpBIiVIbJ5I=,iv:zLeJ1MdDffw072MNKtvXHA/RbAOlXy416DSN24gIwbY=,tag:pFcj9WH6p43A7yZk+KIkpw==,type:comment]
  #
  #ENC[AES256_GCM,data:TM+sf6kGt0G+eoXdaTzu3auo46a7xTuJdZPLLBSJkVH2JZ7iaZ9W3zoFtlxwDVL2VLCAaPX/IjgxnnKVCEJ99b/+NLhitHSs,iv:7+CM5PbCa2ibymVi68pnpksdvNsc6on2LmtPSAMc/Xs=,tag:aEdMgO1bTOPFgC4jJ+yXbg==,type:comment]
  #ENC[AES256_GCM,data:YxbYjQAmLYFgQBvK0IY2am3oJL9MTvDi0cWEHwUQJ/sf24tygEKUHpAOduV7+Hb0GE3kcL7y2i/Q3QEpISu/HeXp/iGV,iv:6+V8NFE7BtvJwhX5VS9BUauiQ4uBpojIg8euK9LSNN8=,tag:qbSUrOl+9fjyXwybGqRGVg==,type:comment]
  #ENC[AES256_GCM,data:ny7NEFO+XRnmytobVAkT6+ImQbWDELCS7nDRaPjfntXPCvpPttK1qP+ROpIcg5PG,iv:wyWBnJaO1SDnXevmG/uinnz71r6KKIMi+DuybQsmbIs=,tag:VjAu2S5Y1kl8Z76fnx4trQ==,type:comment]
  authentik_token: ENC[AES256_GCM,data:ntQ0KpL600TY5z97vHga1t2EYLu3NhAexWweIt3pyHcKWrdkAMecGtGk83MoFcLCCs9XOO4Z0Sew+LPL,iv:D2CbZvXSum4yZOXYV4N5wKt0bnVo3wUffCsywl2VGAE=,tag:lqG1EwUfO39MhL8BH7oW0Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUEc5cWhOT0lFSEJhYXp3
        SEZiKzBZaWlhQm1lcllkSjFLamlPYlFjdjE0CmRlMXd2Z1YrdEJFTWJERkY5Rnlp
        UnVjc0NIcE0xZFdkajFCbmRFcFBhc28KLS0tIHJ0YVA2TnRFZUo1MjBiUHgvbURw
        aHpwdWk4QmtIbTBYUGljamZiSTJGWmcK5ThIATcsvwU6doUGwbcmSREJw1J617GO
        Vo+rKTluU8aSaW4EGUud4MBUgIdz5ljvFHHflhHZb8+cRXs+cZ+SpA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-28T08:38:37Z"
  mac: ENC[AES256_GCM,data:mXS3BD1MZeUrdjRQ3ptfQTl4I71XjU2IZJOSqfJ/vGoHBjmxZpQPDlVcqXNWaop2CL9i5BGtfENxNY7exsdaLe4qgIfbwBXH69pP6r028ZaeMtpAiGst3Z0cuukyPi5dXjHoDO/LV8AvAiJlGKy/fojihqUvkx0ocuTjQPJIuMM=,iv:iyq79b236TJFh2Nmq5BwhmtKogrvSbL6LN2nKSSVLs4=,tag:oTiSFUdMaOV7vQRcxiR1rw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
