---
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:MBASkavrVNJ7y3Wb85CyMrNyVQIVjgrQ9ZTZW+o+z7U=,iv:LSQjfRU9k8Tom8axiEErGdWHe5qkRU0FHNu957yYApw=,tag:XjfejdmTso2sKDZ25vR93w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnc0JUbll0SjJydklINXZl
        RmQ4YUllVjZ3bzdSbXUvZGJYZmRqV1BHMlNvCjFhTmc4WXdqb2ExaUU3OU8rQVdz
        bmxLL0hUb0grd3BHdjMvTVlNSUw2ZE0KLS0tIHRDVVpqbVJ1ZEpLVnkwdHlvWS9N
        U1NRQmNrSC9QQVd6K2l6bGhoT1FKa2sKI90oa6IFTBhW/Z2buQyrJf3AGBqs7xly
        9L6kaAWqVGuJaPAVB9NL7pv9X2J/XsQL/fHbgO/pd34cKKuzifC9QQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T20:19:44Z"
  mac: ENC[AES256_GCM,data:HQJoswiEdkcc1g/X9f9THkxGCnXdcmkqr1W3hUkaWdIkh7mE/Q2q9RhMkMsGxXNs5S0gnRucjEeLqLtXaS7xlEgXCose7QI/Ca5YSpiBlS8buoUqxR+oTujI6tLXn1SjrW8KpkwZN1doIzgzGG1/mxPJo+jjDcQ7MxqOzf5rN9s=,iv:gCcoc70dDY/JQdpV8vCGhBNSww+OZsPIIHijKhp0aQ8=,tag:lfdJK9eDmHAPIIzfvGcbzg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
