---
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:+Q+8PYILtcNUqnoOjQgn1iKoISXsjvyESSaWSx9YfZg=,iv:Nx++560OWUoEviVbEVON6yClOmnTC4EhnXOZP6QT6AM=,tag:mQTAlxa7Yhzw8woiTZl9rQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3S2wxdVorNWhzUU15Y1Br
        SEFDQ2ZBWXdpY1BsUTZhMVFscVNUWTVkZnhRCjd6Sk5hRjRWVk1qMTlOZjB0SnlB
        cldsbDNaMFNKTWp0bVZNbVNUeldPL28KLS0tIE9ZOUtGcEUxZ1ZhdC8wVE9CTFg0
        ZGtkNHJmREdZZnJ0anJsdjNSS0JwUzgK0AjAOCLwfaXoL7e1t286/xkx96pysvTy
        Tu1ath/vTx6ApDuiYKXsbJZugchyX2xRvU1NbQBf0hCFpYAY2ACYCA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T19:50:04Z"
  mac: ENC[AES256_GCM,data:kAL+Yp9zUrB9b4LM8mD8WDEqhFbq/Am/pkRDtk0SZkIq+jG7u+ZerCYZKOxEVoZkcFSJVJK7WP8QXPvBCXSH3NqxfgYJ3TbwAe1Wz3yhIuH47GJgTy/yTidajrbde/XvSqdk2rwK1VIj7fpjiBFEn+kWYR9TmLnoIvBjYLWRB1E=,iv:WmWc9IjJKOlODXkJ30meZwht0JxB3bsZKkuWZF3VySQ=,tag:YNb1cWXpDjqqAUrJRWnD8A==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
