---
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:mUc3pUX53Ret6UJRKy9vWx6rYlDJbfFAXAZ45Jb6SYk=,iv:lzsnadB6ekV5CmDEs/+AxlyKfmX6wpQg4KuQYR3oW/s=,tag:ek7RPJICGYy3vpXy0onEKw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbW5SeEhmWEtRZ25YTjI4
        Ykc1aGQ5ZEYxRXE2bnlUU0JYZWhETEdnS1JrCkpTeWZjZHlLcm5HN0NJQi9KRTdz
        eVBNejVmUXZSNVZ3REN0L25jS3lOZkkKLS0tIG9rNms2bEpsMytZVjlnN0tnNDVS
        OU9KL2dnTjVndUtLZnBCNVdpZXF3MzQKkT6o8BllvpQTMjgicn6ThqA9b7jNAL6X
        DfDVfqU9JjuoLKUCb//GBm9rPHNahPFsJ8bzfpIKYkCpLZI49q7eVw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T19:45:58Z"
  mac: ENC[AES256_GCM,data:EKpzBUTjpJ6tfnf4BUrPsRF8wmIE68RMyv6/CkuCK2wOENV2odskMptWAdlIvFxQarq+oZoNRCXz//HAxFjqVXJZcVOQ1NGM7JzUHTK6T7A09YeXd59DnSdQOAF377VHwL+933I8JtRFt8Hgx9nj4EMH5AsEIGkvDiIZaOmYy4U=,iv:BjH98BF7awOzaGC53DOx8n5SsWu2MQ9emUEHi/A1AVM=,tag:mRyNqY4cNY6QbcmebMP0tw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
