---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: vm-operator-crds
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.13.1
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-operator-crds
---
# yaml-language-server: $schema=https://k8s-schemas.freckle.systems/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vm-operator-crds
  namespace: vm-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: vm-operator-crds
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: "vm-operator-crds"

    crds:
      enabled: true
      # plain == false results in CRDs being rendered as templates which allows them to be upgraded
      plain: false
      cleanup:
        enabled: false
