---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:4EAvwgheeKR6pg==,iv:O/00IEiSjg1Nlx1j/wD5R1ESaysijfok5URPRH9V674=,tag:XTqH86xmFUxOMGABQGCs1w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNis2eEJjVlpJK25kUjcz
        Z0RDNjRjR3gxTzFlVmxnZ01YaU1OZzMzREdZCnZSMnc3aUkrbk84YTVDcXYvWnd1
        VGI2NUQwWXFkcHBrYmhpcXZVRlpuNVkKLS0tIDZrdXlFdHArcldOZ016aGEwcm5U
        UHZIRlNwajVTVS92Q2NMV1lpZU1MN1EKf7WKzsFfI5ETwGg8WImFsZQxK55Roa17
        FGBSKMnLSZRHI0hSmlOpFJjYo2CQJoug5R3QyJTdagyUFP/Yz+ALNw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-07T05:54:15Z"
  mac: ENC[AES256_GCM,data:5SwKLKFc9aUZUEq1l5wGhM3KZyb4VVfKt/9Ix77IbPvmhvIleJzHoKprBXFw5XgkvoJChW3PNiFfen7A6ArSv+8IwC6hw6O1afWUKcnCKoQKT0BXioySOoaE5ZDOsCYaYg/YzaCiai9qQin29J0cLJqNRtYkd8cs3gWGVQ00azE=,iv:8BQsqRMlBgHoWB9tfxhQZHxaXopDzYkrInStsJxc/l0=,tag:vDaoq92z+TGn5pe8CNoyWw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
