---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:B2O7Up8gGlhjOHzUhjQ=,iv:vfDbXyTg6CntOtv62lILos4dwsxsuLEmIOxB7xVTdsk=,tag:tsrWU2AGFEBmsZ0Z0HLiFw==,type:str]
  TIMEZONE: ENC[AES256_GCM,data:tYnbrV4/d9dKm8OMuw==,iv:wcdZ2EUbVaS0CZahK9xSapzd8Xjewrci7rYFkZZpYkM=,tag:Dy3qADGn0LkLuf0dPmNL6Q==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:eMsdCRsSkc6b,iv:dUFTJwfMQ3lVseSPNEXGru2v2kvM2ifxs4ZA/SpMXHg=,tag:mgaNyTA/bF1aQaWyac4GcA==,type:str]
  SECRET_DOMAIN_ALT: ENC[AES256_GCM,data:zzl1TMMiJ/zu9V2UVg==,iv:Oxl7NQnN23wiOmd97aHHyeUfcmRbIhd2b4D4yKgNk04=,tag:NDDHdqVSGGj9BThtGELxHQ==,type:str]
  #ENC[AES256_GCM,data:SK7dKTu2OqGI/rcnPs/4SjLEJIFjPb5If4aWOzIYJwgX3raQVUVcYeN7Eeqkum8pmNcg6fbLJxViULUSEpi/fgKB2wuTunlrP/jy,iv:lj/HvEHwNOkGE8ZJuzbn7wQzNI5LzDdxNll/b4LI3mI=,tag:7yTcFg7vlPZrjCh1Yav0Pw==,type:comment]
  #ENC[AES256_GCM,data:wyPbWIOunn+qDe0W4EkEf6l+g5cEDO5hlvoBA1Khkf75jhOxxrHkUeOdegs/PbnLgx4Q2A==,iv:d1K6EwHjwxkndssusuU3vfmnLcwIkqtoNTPcfAHlYCc=,tag:sZysqWRXoiS+DOtHPaEJ2A==,type:comment]
  AUTHENTIK_URL: ENC[AES256_GCM,data:YH1nkaJRTQVcCjfhh4ruf1HSx+ta,iv:e5AlpN0A/dBdk1IA7GRBL0sxLAgmbwMVavlnQcWkEog=,tag:SiIlCfs+x62DnQYDwjgGiQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxend5eU5TMmlMWjBwT3Zw
        bGhNNTZzbC9kSEVzTFJFcm9wSHZraGw2Tmx3CnJ6RTFvUEdsYWJ0WHZXVWZzelBw
        V1p2YVlBZ2ZjQVg1b1pUK2llVmtOOUkKLS0tIEJ3b2JlTHg4dlBMK2lvOHVjZUxE
        cUFvSDQ1VFR0ck1ESno1Mjh0SnZLeGsKYfXOtcvoPBhgE9iA4xuKoL1bnvZxoH5L
        wc9NxyomNfTHUHqQepZtxNTISdvpEUh1ZV27fKH6ISnjRfXiwYVkQw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-28T08:14:00Z"
  mac: ENC[AES256_GCM,data:OnksmADvIRd5YuTwyoG3pUfqJ3VfyaK0K8qcAwMM7pY/M/A1StQS2jB+bsyriAcsS2aiO7Vxqza3N/akmEg1TvqMtlyyPAUqI5U8HHRL64DmSpTPzimEp3m/2BhWI0S/zGPYvv1Y7i/OWh1J3GSwT8G/o3UbzQJn12XNW4U8n3k=,iv:Wgrgb0d3DhWJkguzkz3Brn9lbU5SlCm8XCciIgMIAjk=,tag:Q5aiy8/hNmRF+BzwAsbL/w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
