---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:sye/CBfb7PI9VDs+I5k=,iv:eLT/TXXe2i1b0wEacLAIM6mrjBUIzZtYXFb0xwVXwxk=,tag:n5usvxm/+6dqfeKu6c+b5Q==,type:str]
  TIMEZONE: ENC[AES256_GCM,data:byGW2gYW69JA5wRG4Q==,iv:eAzZgrUGlq5NtPwsSYDNpy/rSRc2ApR5ZYGTGuSLdJM=,tag:B6Fz4PN7xVKoIDgkVLoR/g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeEk4Tlc4SlEveU92SUlL
        bUwyU2lqZGVXa0xHMGx3cVZqSXVaV0c4bVhvCjA0b3QyREhLWnUwbWVEaE1acVlN
        VVNuRzgxU1lVemx5eXI0S3p6aDNaWVUKLS0tIC9hbkpnNEUvWnZMQnVsaHlOM1pJ
        WGR2TkhnMVMrYlNmSFNsTXd2TlJ0K00KW9lXVyQ2GeQM8MNGfCBzEnSKkiQh/6un
        ZSPDf4uEDSijvoWvYKag/xa+E3tEx1JK5LjXVJZlLKTbW/Ok8fHI1Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-07T06:28:20Z"
  mac: ENC[AES256_GCM,data:h3oAiH+JbQu28IjeQ3eNBU8tIRlYqgzw5Z+oABmjtrX3UshKy4vqX0eUR1a3VYRwOOY1IX8ly9Nn8rodZGKX2EbOesdskBd44qWhja8K05ns/wlAm9Qba8rhtRmlMoznM3cmbUtovxLaUMjIzY4vc599ucBRB7Pacvv1AEqGiD4=,iv:qRZg+lUkJIErTl0KZtL11WLtn+QC9bD0h4xaj1kwhks=,tag:xHxa0FhQ8mUWV6lnNygY+w==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
