---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:n+BGhtCBpOAOomiXwe0=,iv:hXLkodDywLIEFS8KEna1SVoN5td6C9tLtdhnnWvZgkM=,tag:Bvg3eBlRyBktnyFbo0vawQ==,type:str]
  TIMEZONE: ENC[AES256_GCM,data:R+rMYxHhFaXB6PZ/yw==,iv:/twwJQ9XIEM0ZJRYA4ZE0jn0hcKee+OFWpSaxKUQ3Sc=,tag:t8pVRiMeO10QBnM78aYcfw==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:RBTk43TA6Hq0,iv:48S28f9XOqJTSKYBVt5YgPcWkkaH1p4IUcZrg2INN+g=,tag:xtKuhAzyqSLx9qHFNts2uQ==,type:str]
  SECRET_DOMAIN_ALT: ENC[AES256_GCM,data:Rb7mPdgMg10F92Mq3g==,iv:T9XtBHOdMQ5QKtBZ7t/VMQm7KrALO+JUSvYDteiBtkI=,tag:EhVCvCiS6rWnbURelUlaMw==,type:str]
  #ENC[AES256_GCM,data:gqwJfeVHLh+Zpu/hpYlS9Xj2+x/kWIeZj3zs3atDj/oYuZLZpXq3Rb2i00XGWa2S2hB45Ymf7Dos+pqQ4HFwJqdB,iv:sanLdbfmaEnF3T77/KTu4pbUX7f+vf0g/dW2ebymbVE=,tag:Pg6xPPkiTaxMk0fLXRzP+Q==,type:comment]
  SECRET_DOMAIN_REGEX: ENC[AES256_GCM,data:jvwwDXV3ECyXHA==,iv:izLgSVR/pw/Ha79e/ZzZyD0xhjUxSuFsIbzPDQofeCc=,tag:kkynNxdAZLYBoxqUKGykDQ==,type:str]
  #ENC[AES256_GCM,data:5rELcjeXK4AdjmlfO19MPV/3C6njLnFJisIw99+uXZLkpGUeDzAO85PCygdJHNkyfUdT5nn5xZbprYMxm/EHNHeSHn6RAQQm7G0L,iv:OMCbhIw3IQp1rrStXyO8NgHffbyz4pCuquhujW6V7mo=,tag:H90xgalnBZfkulb9wTNe6A==,type:comment]
  #ENC[AES256_GCM,data:YzZ5yCgZ2PIazPlyExzE1euZItV7wcQxK1awdBCJBOu4jjaphfnjlI8++8CLdlMtGTIvBA==,iv:d7jIHVjNXwj+7DYoldmbF4BM1Z6PnaMsgd2dkQFHBos=,tag:ChK7gx6IqLY28HcEZpLdjQ==,type:comment]
  AUTHENTIK_URL: ENC[AES256_GCM,data:zanrdRe8TCt3EkcaFDtIpVaVvxRV,iv:k3PAJE18TAoFg2oizBgsR98U4dH90Q7Cme2c++y4Kg4=,tag:LuB1C6Kmoza1KknopUmc/g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURVRpNHNsalJ0eVZ1TG1R
        aVk2VnJ4MGRrTFJGMW1IeVRIUjZCVUhqMm40CitWWm1NTUlHRDdXWEYwaTNlSXFp
        MVZFMGdWOEwvaUZTejJVZjkwb0RkdFUKLS0tIFU2ZWh6K3RaMG01Q1Jlb1NUZG5R
        citxUFFZOVhaclc1dWgva3NZTGVzdjgKTPzhkEAGxPUhosJe9Q9l/JgAQ57t3fyk
        J1hqxs9llW/Kyez5s+or1yGGx1hlkmOUIJ7vc+t0hHhdslvUjdfDsw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-18T16:43:21Z"
  mac: ENC[AES256_GCM,data:DeOI4HNmXQ+oPHwREfX/WvrtkgbjXH6Arb1hLPEU+VUjTpzhQmr3iY81pGp/T4ezMO1MM/pF+e8T8/0lV+mPB2/v8/MBtkPnuiSB5gvJkIbNQjf/coElopfnFnGy//rSYHVumbZmBPPRAMzTb125ddGxu05iV64n/Kd/T/J0WgE=,iv:51vd42XRcakIuREWsJRfp3ZIuzRNW6hMO7sqKBfJs3k=,tag:LD/hCp3iFUan/Tv/Av15Sg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
