---
apiVersion: v1
kind: Secret
metadata:
  name: maxmind-geoipupdate
stringData:
  account-id: ENC[AES256_GCM,data:VQ0NSndSzg==,iv:P5wIQipD7Wc1KvAFvtesYd9CsgQUvLN1UYWQxfUkWYg=,tag:BDT2fuZqA0+Cwj40cFZvvA==,type:str]
  license-key: ENC[AES256_GCM,data:rGttQt474rSxn+oeu1E4am4l7IMysIloq+q3Js+TYhVHGz4Nnx1sTQ==,iv:5rFkJUp/J8ST1LeZKCMzvea9YOdsQa/MBgAqWipQYEk=,tag:0eghEIfGLxPyMMUh00GkuA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSDVmZ2ZuR3NEb3dZQk5u
        ek82aXM2MUdvYndEZ2dBK0krY2pPZERjKzJ3Cit6M3ErVmFEelRjdUxRU2l5S1gy
        UWJmdDlNQkx2bWFDUzZSbzQ3UGRZVkEKLS0tIGhhRVowWTFWSVBMdEpESW1JNXI3
        QTBQN0R1TlA4cTNzcHhYcTNacHdhODAKHnXQsAZTrcBbpViBM+x5xisQbw2QdXmn
        8BTeW0NDwxu82XIaVp5UTiiDFofjfJ4jQYXAdIsYe3aRT7TBvXp9CQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T12:00:28Z"
  mac: ENC[AES256_GCM,data:wtL4juFSIGfMzUrOGTZzTyQUniUue+qIqxUsWsZjFdoa2fwMDUDozib9rbo6LsgJmDHknNgNeHPODHQAe0FKdFD340SvyY6hjhvwDtnDk5JHNH/K5jYjJtV60NZxIv1Cfunoz6Km5hHqISSIJT3NwNFUUQqJ8Eq0kRQDaOgAoJQ=,iv:RVD2F8UNhV5xcluFB/0TlyMUEEcUOca7qxInR/pvj1Y=,tag:Hh3rmeBP/qs6ZNAJFlJuuw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
