---
apiVersion: v1
kind: Secret
metadata:
  name: maxmind-geoipupdate
stringData:
  account-id: ENC[AES256_GCM,data:2vxytnNnmQ==,iv:QqQlFdfWT7cLyUWq6rZRogf3cTzu8xinAYz84OAwbyQ=,tag:oxy97Xcczjj6Jr/WCA6aGQ==,type:int]
  license-key: ENC[AES256_GCM,data:rGttQt474rSxn+oeu1E4am4l7IMysIloq+q3Js+TYhVHGz4Nnx1sTQ==,iv:5rFkJUp/J8ST1LeZKCMzvea9YOdsQa/MBgAqWipQYEk=,tag:0eghEIfGLxPyMMUh00GkuA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSDVmZ2ZuR3NEb3dZQk5u
        ek82aXM2MUdvYndEZ2dBK0krY2pPZERjKzJ3Cit6M3ErVmFEelRjdUxRU2l5S1gy
        UWJmdDlNQkx2bWFDUzZSbzQ3UGRZVkEKLS0tIGhhRVowWTFWSVBMdEpESW1JNXI3
        QTBQN0R1TlA4cTNzcHhYcTNacHdhODAKHnXQsAZTrcBbpViBM+x5xisQbw2QdXmn
        8BTeW0NDwxu82XIaVp5UTiiDFofjfJ4jQYXAdIsYe3aRT7TBvXp9CQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T11:54:05Z"
  mac: ENC[AES256_GCM,data:FhWev3Rw1yuIZE/ZuMUC1O0vFC+DnkhJQK4nTtwXTeoCTGZ0v1v1viDU/1fue+YGYK5roi8pr30DmUlOw7/Scci+N0RVtLq8aiFT+bMwUOq1finwm3GYhxmXiKPR5zVPWz274WOnngjOcRU/KygkfUC6B7yocWpl4fhy8us/3fQ=,iv:YIwY/u4ONp5cWKH7NGl8A82NHauXKfCQHKqX3nOzc+w=,tag:LHdA5EDq60l6dvtkZSuAUg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
