---
# SALT_FILES hashes download passwords; losing it invalidates every password-protected link.
#
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: gokapi-secret
stringData:
  ADMIN_EMAIL: ENC[AES256_GCM,data:gxqWlgstznxEVpS5+g==,iv:IxJwcwhzPOavoGmZrbSb8FBYANFkplewX0wc/eMIAw0=,tag:ykaY37SjFcoqOsnuhLL8ug==,type:str]
  SALT_ADMIN: ENC[AES256_GCM,data:kU7jcOhOInhsjQ6KqsuJe7bFcWX8Eu7GYCAt1xg9tIYQDoF4HcgcXA==,iv:IQHQjU6l9SOBRSyDLjPqG8JsK19m3oWOVGPM457pN68=,tag:yndh/UglTDjPPLMa1ettuQ==,type:str]
  SALT_FILES: ENC[AES256_GCM,data:WCcRvAAHBOaIBBGteFeE1kBPIAcDnjoGgh1e/0ZErx1GDiZgsx5IOQ==,iv:m3z7AIXsI8L2z//o4klBRRpK355u2wf4/ku2aPV8JT8=,tag:i+DeF6HLhOe7H+caQf3POg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2S2c4dXJzSVFDVldSNVFR
        YU9jUzlGNmNNblZsUFlESG9FQlVVY3hsL0RJCitiT0lDTzhyWkc4RWpBNWFha3Uy
        bzlDOENwZFcxNTRKTUVBY0p3WFFlVjAKLS0tIDdUZk54dHJHN2V3YW1uYmNWT2g3
        MCs1QmpTQ0dLeDRCc3JyUUxRU1R0STgKZwEUrG82eJmEEeZdxtkhc8itD7KH0JA3
        Gu3JcPT/UA/A7ulmEwcDUC/LQDqu8HDh5uy26zI1cTskGL9SjGJCRg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T09:43:55Z"
  mac: ENC[AES256_GCM,data:9vIdUqGjUg7FkWd4bK5KF8QUgc1YxFUBFaIH5bVKbL8xxA62EbFKgLXr0+vpOqw2Lt/U7VPVIJlNZmkloHC6rTHUTIsHrXQzQSdxeQBw0kxmuZl4dS27rv7wrgTUcSEkqwArRJs5p+UTwyn/+MUJhxbcoTcYvL80NXF53fC++Ts=,iv:ES6ARuQZ/mghwJ21axK0rcwo1vntnGUOZ1MrKLxwqTQ=,tag:s3xYdDw5RmnKBCad0qKHyw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
