---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ciliumnetworkpolicy.yaml
  - ./secret.sops.yaml
  - ./ocirepository.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: home-ops-runner-hook-template
    files:
      - ./resources/job-pod.yaml
generatorOptions:
  disableNameSuffixHash: true
