---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./grafanadashboard.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
components:
  - ../../../../components/dragonfly-shared
configMapGenerator:
  - name: blocky-config
    files:
      - config.yml=./config.yaml
generatorOptions:
  disableNameSuffixHash: true
