---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:BHZqcrGUywdkhHx8mq2rrAxwPGPdWGCUQPiV79WYxl1JPAOEBiJ8pkXvULX+LJ7EUPqtJGBHt+wCIMdxhT5whobZpYO+WW54B9j2qMozJXWH3tzEhR9Sfmy4vPYC1DriMMGapYXnSlkALTpCNKTVyZNmM10GqpA/D6EojhLdPLKiqy4rN18UErYdLZ9CznSA1rqhjiPF7rr0sRJM+Byc8cPTZD6BRJfC7FnL06d9WXryz0tA,iv:dQQavolvLYgZcz+1a91iwsxZYBmEJoV434HTgT9NkiM=,tag:pj0IzrjEnhX0hXQ330md2A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhL2FqeVFxbTJOTk90ZmZC
        bDBPcU02eEEvZHMwQXJwdGRFbmxDalJQN1hFCkdKejdqbnlKWUFvZHZnOGY3UW5j
        bkYzSWVBSTBtZFllSDZ5TG1MOHhndmMKLS0tIFRQaS8wUFVCRnM3ZDNRVTdJZVdl
        OWVmOHFZMFVlYThRMEpvOW9zeE15M1EKftGZICphbX+PJgMBZzo9hsNUvdDGARHO
        tiJDdW3kFEmuouq42KkDJHYWzP8Y9s93sH40/RDxWzr1XhPM3sAY8w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-05T13:56:31Z"
  mac: ENC[AES256_GCM,data:maVfRLgbNYyN1fmdvlFcsWaicTDKAEj+2/Y4HK8NQ6Q+RZWR4Eu+TxbYUeLf+mH2F1rk0G5VOVcIPpUJkeW5NtUnubkqZ6Pe0uZky9aclBDKiEbvtzqH0/bWpuXjKf3TaR8I8DhGxYwRthgLxXBnj0RLzpLzD9cbUTLxwDDTu9c=,iv:pwSmHFOpkCUbnwfJFNJNTuk+471BhwvuT4pRWsL9uJQ=,tag:UEXc2IzTiiXf9OH6Ub2RZQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
