---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:3Zihg3rD1/+7XJ3jNIBtkPLeWwk/Q/VoPavQQO6OOwP4VF+DRc9zUEXq1eaNnkOV3DlrFnESXXl0ZjnAcZWgLHpmkQZLEziyyzsX4n0IaEpMz7B+Ekqqd+KdycIeE5qxyMqLDpg5o3rfz1vSi4Pmnq0QUDHAzJhp5NbEv3cWI5WvwbcyTdRWlE2er3o4kvy+p9wisWHWR8gAIrnf/vHkbHnUIZbfZwdYWx+S//RlsQ/cenu7,iv:ADOtYOp2obEbnlC/y6a6D6pS5O1JKwR54Bk8KOpBBpM=,tag:1kIP44QkFui/itZIrK7Gkg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrejJiV1V5Sm9ob3hObGNT
        RDBVMkRhNW1vU0FrNW0wdHBuQnFMTTVCMGlBCit0MzhqdDYxeEI4dUFRY25NMm0w
        WGNEY29Gd2tUMWxBVCtGS2VpOHBOS0EKLS0tIEdWMDJLT1NVVmJLNUZic20wMzg3
        RjhFUUNLU3VZQU1SRnJuc1BoZzZhRW8KFielwNhFbWbaodo3AIeysiBKj+vFaDnj
        ugPqnKwiSoLq3zIjm1fhBoaA3BVfWenpkCq77Evr5e3pS55EWc+hHg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T20:19:44Z"
  mac: ENC[AES256_GCM,data:D8eAr4UDIa3ZB6woVaMMoqhUrTDnr/eBUTwRZQheU8yPISdXCb3MGDvHr6oOEBHxPfDr5v2HJMNUT4NkpRcSlAYyrjiplCjEkxU778iMpxD7QSD9ppsrSbt0HcnF3tbM2PqnSkopYDw1O1M+BAxkmACd8LcscEZqsQbJ5YpC4E8=,iv:st8ZUItWceTF17SRP4PsSd4G76+1QTZPUyBO1PpEZ5o=,tag:CY4UOYgilB0wuHCCiN6v8Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
