---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:oEtgUvw2NN4sJ1WMCIpYauaZlHyk32sG+NaFC5EJIlCa+9hXEGDjGVQpRJHLFg3Ty2uDAR82xulVBtaCoSK54HacH7g/MdVZsZRUGulChnLLj9V2QsmJRYaPYvHxnsDlrILwa3f2RrESCzmNFvorh7caiX+5tTu2VHisUMgoExKaxMD/QiDvy5ImAR9Wx1ia8pGzwsF+CxpI3vMXa7Xnteqwin8NNWRUaYHWKMuxbdBahY2u,iv:9Ou297hC7QtjMU4XD3RtpKQ0fzajRY4veBHtnirPAv4=,tag:L5I/OhD/AxdrAMdvr4p16g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArblRLTVVFQ2k4T1cxQ1pq
        NjRPa21xRFUvZ09xenBUbktLc0tNQU96VnhnCkxhN3FXZTB4bDRzZDZ3RnpNSkdq
        UmtVaHQxZzByc1dRVFlTamNGVjlENjAKLS0tIHU3UWdPdlBZVXp6dmIyVnNRckR0
        RnFNQXVlbGJVdk5zVjhDcjlHQld3ckUK+zyiAQRN3QgjQ+KeQsNIXTmfFZBRuu+V
        jCxTpAlWPOIyEIXiOa+rPNHcM1Oy1hTgQE27YCGkzemopz5NkD1o2Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T19:45:58Z"
  mac: ENC[AES256_GCM,data:aHAIsHnL+kGgYOMFhNU6atAPslNONTeRT4vc2PIKjif4oFYqv8TCovhGOCpFibLeBqEXvwD0NO6ex4K3sR9YJ0aQ4VUOmHHaCDT9Lg9TIM7evryHAwu5EWatjRFXve2FgvPDWQEubW0KSjjs6ZrDqa3k89k9/BkKXPP7J66pb+c=,iv:GEpDAG0r1GXOga/L5uIZsrrheBioNjYnJ2owN2AWsLc=,tag:ZIZrNF5o8k8aRZOU3O1doQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
