---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-logs
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.13.6
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-single
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app victoria-logs
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-logs
  interval: 1h
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    fullnameOverride: *app
    global:
      image:
        registry: quay.io
    server:
      retentionMaxDiskUsagePercent: 80
      persistentVolume:
        enabled: true
        # existingClaim: *app
        storageClassName: "ceph-block"
        size: "20Gi"
      route:
        enabled: true
        hostnames:
          - "vlogs.${CLUSTER_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        extraRules:
          - filters:
              - type: RequestRedirect
                requestRedirect:
                  path:
                    type: ReplaceFullPath
                    replaceFullPath: /select/vmui/
                  statusCode: 302
            matches:
              - path:
                  type: Exact
                  value: /
      serviceMonitor:
        enabled: true
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 30m
          memory: 512Mi
    dashboards:
      enabled: true
      grafanaOperator:
        enabled: true
