---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: lan-icmp
spec:
  module: icmp
  prober:
    url: blackbox-exporter-lan.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - 192.168.1.101
        - 192.168.1.102
        - 192.168.1.103
        - 192.168.0.250
        # - 192.168.1.53
        - 192.168.0.1
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter-lan
      action: replace
      # ---
      # # yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/probe_v1.json
      # apiVersion: monitoring.coreos.com/v1
      # kind: Probe
      # metadata:
      #   name: lan-nfs
      # spec:
      #   jobName: nfs_probe
      #   module: tcp_connect
      #   prober:
      #     url: blackbox-exporter-lan.observability.svc.cluster.local:9115
      #   targets:
      #     staticConfig:
      #       static:
      #         - ${NFS_SERVER_IP_ADDRESS}:2049
      #   metricRelabelings:
      #     - targetLabel: service
      #       replacement: blackbox-exporter-lan
      #       action: replace
