---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app dragonfly
  namespace: flux-system
spec:
  targetNamespace: database
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/database/dragonfly/app
  dependsOn:
    - name: dragonfly-operator
      namespace: flux-system
  healthChecks:
    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      name: *app
      namespace: database
  healthCheckExprs:
    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      current: has(status.phase) && status.phase == 'ready'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 1h
  timeout: 15m
