---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:qsiX3JfYroLzUcX7mt0SmfXDQz1WYji/9d62g74GEAKknRR7FZE2PQ==,iv:oGjpeEDwOlbFKyKWydICHmBei2eq9MwAVuYXI+Mrmao=,tag:fW7XGP40RLA9GfQmczL2+A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycm5lT0w1WGRkRzFDazRr
        TU5ZcGF6a0c1c1N6UmxGaXBYWk1xcHkzcHpFCndMbWZpaGZpbVVWYWlvUCtDeVdZ
        NkxwUTZCeFRjcWE1MWFSc2VndWVuL0kKLS0tIGUwOTA2TDR1ZE5OOTVvTnl5VCtk
        VkFwUVRQRFgxZkdEa2EwWXkzd2F0bDAKAqrN7skET6uAEqd9fKqkIgUQXBzplPlx
        19mQV1hbE9511ao/UEi1CeJ4ILc0A58nhKqkF4ttDorQfOnWXw4s2A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T19:45:58Z"
  mac: ENC[AES256_GCM,data:t/3/TAA99wC67X0zZ5IO3Touj91b4Up5tp5N++2aoJd5+xPBz+0jufy8Mieil34l29nfUHAzMVWOIeiRkCYYQD56fC3guX3vlAqKcl2vZ3lULthZeUsfpbabUHIu0eKq/CEwkHdYp5PnyJPD2J9wH7b7ixGstJvE9yfet4KXyww=,iv:B7XIl7nsv/agekd4le4EYNeOAi+3WV+Cyl8bHPgWvxc=,tag:XzRw/AVPWROkTQ5cKpY1BA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
