---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:uSwoJ/w3jxUD2LfM6QUFAL6qGSTK5ihdm2dnAQTcFMr6VfLe8u7gjA==,iv:jTXS2MVM879OvcjH1mFjrY6f1kMlYBaS95y/IsbBuzU=,tag:NBppKAhnRdVL7+Ijyh00aA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWnV3KzNVMTU2cUR4M01w
        MlZXcUFhcERXcmI5ZEFMc3BXOXlxem9uRlJRCk1nSTNkU1ZvdVJyRkJIdFhFNnpG
        SWd6QzJIUEl3MlJkdG93d3JhTVFKWEkKLS0tIEd3dDFINERGMUwzcVlzNmF4TDZt
        RTNUTVRJbEI4LzU2UmoyMW14bjNYcEEKqCb3agTaK1qE+vS+UFSZGMp26iSGCTSq
        Y5wJArr8fhoYxgrzfcNoVOthfNdqQxLJDIo9quNYvAkl2shfpAm6BA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-06T18:20:50Z"
  mac: ENC[AES256_GCM,data:xtUnbGNFJ2N4+AxsmBo9+gones2vwA3TFHkX7gv/C3T/Zhde9bMPqGGfoUC0znExA8MAZEZbSajVHhkKxoVGV3MPEj6Hai4TAwIT4ycFSPLfzGDNpHS8EAOzQ5sH8UBizT/5xb61tWHLoTYCWYDsJ1gMLGZhhnvyI+qyi1YhsTI=,iv:QvqUKS2HVKJdab7xfhpYnmvhf1IH9zK2JZSUo8GSa7g=,tag:2fZLCuzhgXD1HpHPASVFxw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
