---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:1BiHXZok39gk75wmpKPvUKIGUXumnGlgqanPWnokzzZrgpM445qo3A==,iv:o7a9gjAJ9xndYxHUZb976IMz3HHvkp7raHIacc+kA4M=,tag:zbXH088D9Ki2FrBztIdrPw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaEFkUTROK25SZ1dxMEIv
        dHNsWE0xRW1mTm5OSmVwdGc2eUFsaGJPWWp3CmZQSUpkV2NDamxjSXVLV1pCVFNx
        ck5kd2p2MERxME1HUWIzajQ1UU9lSkEKLS0tIHpHT205NTlPMmR2TDhNa0VSNE9Y
        M2w2Uys0UTE1K24rdXNOQWl0VFdBeEEKx59TOpz93Z31CNOvkxj/j2GvHfQecqHy
        oyr/4Rj73shhGFDXxVwu4rN6eZdwZKzi43OBOy1iw71l8KYnPyTvUA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-05T13:56:31Z"
  mac: ENC[AES256_GCM,data:UrPPGQy/f+SsSnQ674lqmaZ2aYXS/1Gkp+7avtLnyClTphB0FNJ0UUWuQ+Wud2tI1+yugM7BbsQC6oCklN1jVqNS7B0vOOzxzsWxKJIlqyXVTn3GqaXmzXWTezW45QMXnNQtI5tlKdUt2znRg3lSjWRxLFPdTurw9HwgrRKo0AI=,iv:WZOCgJqKv7aTs4zLEGbgqx88IA4RKOELFWw7/0CrnpA=,tag:2vsfdSoMtH5Hz9q3YUd8DQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
