---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-pg-shared
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: database/pg-shared-${APP}
type: Opaque
