---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Must precede the Dragonfly, which cannot start without its password secret.
  - ./externalsecret.yaml
  - ./dragonfly.yaml
  - ./grafanadashboard.yaml
  - ./podmonitor.yaml
  - ./secret-garage.yaml
