---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: dragonfly-auth
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:+3B2AsqJE6H0tPMjaMH4Tgb+nmvTSTNeDN9F6AM/iZXha4urv29N5g==,iv:s7fB+TV5xcggFJvRbINpQYdEhkUIGoRhQDsJS1vJgoU=,tag:yxj239Z7TXmIHEL00do+iA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibVUrT3U2dWYvcjNSeUtt
        STRZcHBCZ25BQWVkOGR1cHl4b1k5Rm0xSVNZCm40eHE0K29hTnZsV2g5UmpkdDhL
        SlFSc2UrT3RqZ2lvYmkrZmpId25mQkkKLS0tIHVzempUVlkzd2ZmYnhuenBHeDZ3
        RTdmS3pIUDRhejJSMFZhTVNJdXpya3cKIUv+u+9cxlF94yqp2gjnMWhdnC35QpLh
        cy7Js0qa1zn1A+XJvwEf25o7Zb6t3cKjGUPIqYFphHK8sx89mWi8vg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T15:22:50Z"
  mac: ENC[AES256_GCM,data:out11LIuef/YvMZzpEmbs+LF8q6ZuDv/sGdzOnY41unMWN3SexxBUBlEC7pGCFT300K+2vVo/oegFDE4+GQGX432nrCa51ATyxHGLq8DfBXjv5lqVNXVfunRTbPiynjzvy7x4rg31Va5ZQ4fEvBtWrE9moYlbNc5cH0uCyJziQU=,iv:2hgCYWf66im6vQ61ERNBFZ/nmI2KbbzG3e5m5/dzWVk=,tag:AK9ebymDj4VFFQ/Cu9JmFQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
