---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-dashboard-password
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:FaL1enlBbhwKCg==,iv:H24mocVTrybIZrjMvdzpujwsNRjcG8xO78KLTQs9m9Y=,tag:cv87lOcuqjWmq74YcTkR0A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBR1B6SExWWXRNZzFaOHEy
        cmQvd0huSWVkS0dBM1VQcmVmTVJwMWMrMzJJCmtNZ1E0bHNhQmdzSHFrbXJZdTNV
        QmJFWVUrRGNqZ0FJbll2SVVISUJpT0UKLS0tIFFrdENIcjJQL1VWd1FMdHRidFBm
        MlV2YStXME0vME9JM2hlZWQzbjlac0kKJ10bv7vkl/qw2O19TsE5QotXxbr104nq
        rmeJUMfc4Ee2iR3YzJVOrk/7XztSRWALqLZykYz3/EetFbH2aUUT7g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hxyyusztx42n4ympwpu8jwzyvegzd8ynzl3jeve952rewvrj2aesy3s74t
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-07T06:10:18Z"
  mac: ENC[AES256_GCM,data:Uu+sJXQIfm+7g7kvLBT3drrKxwnIvDnLaznBwaEMpZvKGeISWEc/PcGnbObT0kV89nGj62DfJHXBpKQk2D6/++AUISzLxX1Vd1+cez//qZsKW5xJZeqwcKffqSIZKcNpfDCN40gUYbZdxTFkApzv6Oh0VAjeCFrjkOP3u3yiRqY=,iv:LFgMMLgsWydHcVSZIvDgI0y0B0S2B2HcnOtMDiMRXNQ=,tag:CgQAzlf8v8cvgh+inhJNcw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
